name: obs-configure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    container: ghcr.io/macedogm/rancher-obs-image:latest
    steps:
      # This is a workaround needed for the .git dir to be available inside the container
      # See https://github.com/actions/checkout/issues/335
      - name: Configuring Git
        run: git config --global --add safe.directory $(pwd)

      - uses: actions/checkout@v4

      - name: Configure OSC
        env:
          OBS_USER: ${{ secrets.OBS_USER }}
          OBS_PASS: ${{ secrets.OBS_PASS }}
        run: |
          sed "s/OBS_USER/$OBS_USER/;s/OBS_PASS/$OBS_PASS/" rancher/oscrc > .oscrc
          osc --config .oscrc init "home:gmacedo:rancher"

      - name: Creating/Updating projects
        run: ./scripts/manage_projects.sh

      - name: Removing OSC config
        run: rm -rf .oscrc .osc
